### ISSUE TITLE
hiseq atac covert bigwig file

### ISSUE THREAD

**Issue by BioInfrookie** [bakerwm/hiseq_dev#2]
Local：/home/qzh/Analysis/gl/YY470_Pias3_KO/03-qc/ATAC_B6SPR_WT_rep1/bw_files/ATAC_B6SPR_WT_rep1
cmd：`/home/qzh/anaconda3/envs/hiseq/bin/bamCoverage --bam /home/qzh/Analysis/gl/YY470_Pias3_KO/03-qc/ATAC_B6SPR_Pias3KO/bam_files/ATAC_B6SPR_Pias3KO.bam --outFileName /home/qzh/Analysis/gl/YY470_Pias3_KO/03-qc/ATAC_B6SPR_Pias3KO/bw_files/ATAC_B6SPR_Pias3KO/ATAC_B6SPR_Pias3KO.bigWig --scaleFactor 1.0 --normalizeUsing RPGC --binSize 50 --effectiveGenomeSize 2652783500 --blackListFileName /data/biodata/genome/mm10/annotation_and_repeats/blacklist/mm10-blacklist.v2.bed --numberOfProcessors 12 --extendReads True --smoothLength 150 --skipNAs --centerReads 1> /home/qzh/Analysis/gl/YY470_Pias3_KO/03-qc/ATAC_B6SPR_Pias3KO/bw_files/ATAC_B6SPR_Pias3KO/ATAC_B6SPR_Pias3KO.bamCoverage.stdout 2> /home/qzh/Analysis/gl/YY470_Pias3_KO/03-qc/ATAC_B6SPR_Pias3KO/bw_files/ATAC_B6SPR_Pias3KO/ATAC_B6SPR_Pias3KO.bamCoverage.stderr`
Error：```
usage: An example usage is:$ bamCoverage -b reads.bam -o coverage.bw
bamCoverage: error: argument --extendReads/-e: invalid int value: 'True'
```

**Comment by bakerwm** [comment]
`fixed`
change the default values for `--extendReads`  from `True` to `150`

**Comment by bakerwm** [comment]
fixed, since version 0.0.5
